### ISSUE TITLE
lodash vulnerabilities in 4.0.0 

### ISSUE THREAD

**Issue by alassiter** [thenativeweb/tailwind#10]
the 4.0.0 release depends on lodash 4.17.11 

it also depends on flaschenpost 1.1.3, which in turn depends on 4.17.11

There are known vulnerabilities with lodash 4.17.11 and they are being reported on npm audit. May I suggest updating dependencies to:

- flaschenpost 3.0.0 or higher
- lodash 4.17.15

**Comment by goloroden** [comment]
Thanks for bringing this up 👍

Would you mind submitting a PR which fixes this?

**Comment by goloroden** [comment]
Closed due to inactivity.
