### ISSUE TITLE
Sample app?

### ISSUE THREAD

**Issue by blissi** [thenativeweb/tailwind#2]
Hi Golo,
is there a sample application somewhere where I can see how everything works together?

Thanks,
Steven

**Comment by goloroden** [comment]
Hi Steven,

thanks for asking 😊 

Unfortunately, no, we don't currently have a sample app (although it may be a really good idea to create one).

While we don't have one, can I help you with any questions you may have?

**Comment by blissi** [comment]
No worries, I'll dig into the tests and play around a bit.

**Comment by goloroden** [comment]
Okay, great :-)

Then I'll close this issue.
But if you have any questions, feel free to open another one 😊
